### ISSUE TITLE
plain `swissmedic-diff` does not seem to be working

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/swissmedic-diff#4]
1. `gem install swissmedic-diff` latest version, with Ruby 3.2.0
2.  `swissmedic-diff /var/www/oddb.org/data/xls/Packungen-2023.08.08.xlsx /var/www/oddb.org/data/xls/Packungen-2023.09.08.xlsx`
3. Results in

```
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/swissmedic-diff-0.2.7/lib/swissmedic-diff.rb:158:in `describe_flag': undefined method `strftime' for "unbegrenzt":String (NoMethodError)

        sprintf "%s (%s)", txt, row[COLUMNS_2014.keys.index(flag)].value.strftime('%d.%m.%Y')
                                                                        ^^^^^^^^^
Did you mean?  strip
	from /home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/swissmedic-diff-0.2.7/lib/swissmedic-diff.rb:330:in `block (2 levels) in to_s'
	from /home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/swissmedic-diff-0.2.7/lib/swissmedic-diff.rb:330:in `collect'
	from /home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/swissmedic-diff-0.2.7/lib/swissmedic-diff.rb:330:in `block in to_s'
	from /home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/swissmedic-diff-0.2.7/lib/swissmedic-diff.rb:323:in `collect'
	from /home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/swissmedic-diff-0.2.7/lib/swissmedic-diff.rb:323:in `to_s'
	from /home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/swissmedic-diff-0.2.7/bin/swissmedic-diff:47:in `<top (required)>'
	from /home/zdavatz/.rbenv/versions/3.2.0/bin/swissmedic-diff:25:in `load'
	from /home/zdavatz/.rbenv/versions/3.2.0/bin/swissmedic-diff:25:in `<main>'
```
[Packungen-2023.08.08.xlsx](https://github.com/zdavatz/swissmedic-diff/files/12793948/Packungen-2023.08.08.xlsx)
[Packungen-2023.09.08.xlsx](https://github.com/zdavatz/swissmedic-diff/files/12793949/Packungen-2023.09.08.xlsx)

**Comment by zdavatz** [comment]
@ngiger says:  I think here Swissmedic is using suddenly "unbegrenzt" instead of 31.12.2099. Should not be a big deal to fix that

**Comment by zdavatz** [comment]
Yes confirmed, opening the two XLSX files and replacing `unbegrenzt` with `31.12.2099` works.
